services:
  django:
    build: .
    container_name: baiano
    hostname: home
    ports:
      - "8005:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DATABASE_URL: ${DATABASE_URL}
      X_FRAME_OPTIONS: ${X_FRAME_OPTIONS}
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 baiano.wsgi:application"
    restart: unless-stopped
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
